# Generated by Django 5.2.15 on 2026-08-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='bitrix_first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bitrix First Name'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='bitrix_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bitrix ID'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='bitrix_last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bitrix Last Name'),
        ),
    ]
