# Generated by Django 5.1.11 on 2026-08-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_telegramuser_bitrix_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='bitrix_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Bitrix ID'),
        ),
    ]
