# Generated by Django 6.1 on 2026-08-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options_remove_task_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='source',
            field=models.CharField(choices=[('text', 'Text'), ('voice', 'Voice'), ('video', 'Video'), ('photo', 'Photo'), ('video_note', 'Video Note')], default='text', max_length=10),
        ),
    ]
