# Generated by Django 5.2.15 on 2026-08-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bitrix_task_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bitrix Task ID'),
        ),
        migrations.AddField(
            model_name='task',
            name='responsible_bitrix_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Responsible Bitrix ID'),
        ),
        migrations.AddField(
            model_name='task',
            name='responsible_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsible Name'),
        ),
    ]
