# Generated by Django 5.1.11 on 2026-08-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_bitrix_task_id_task_responsible_bitrix_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bitrix_error',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Bitrix Error'),
        ),
        migrations.AddField(
            model_name='task',
            name='bitrix_synced',
            field=models.BooleanField(default=False, verbose_name='Bitrix Synced'),
        ),
    ]
