# Generated by Django 5.1.11 on 2026-08-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='telegram_file_id',
            field=models.TextField(blank=True, default='', verbose_name='Telegram File ID'),
        ),
    ]
