# Generated by Django 5.1.11 on 2026-08-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_telegram_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Idempotency Key'),
        ),
    ]
